"""
This module contains the template used to create QAutoLinguist configuration file (.ini file)
"""

#? The reason why this is not generated dynamically is because config file alyaws remain the same only with other parameters
#? And it is not necessary to overload processes, only a simple format.

#! The template must contain the same formats as config declarations in config_decls.json, reason is because config_decls are the params 
#! that we need to pass to QAutoLinguist.
INI_FILE_TEMPLATE = """
# =============================   QAutoLinguist Configuration File    =====================================
# This file is auto-generated by qautolinguist.Config.
# If you are not very familiar with the configuration file format, 
# just fill in the fields in the "Required" section. 
# Be cautious when placing values.
# Take these measures:
# 1. Do not use "" or '' to specify text strings, even if you want to specify paths containing spaces;
#      the parser parses them internally; it will cause an error if you do.
# 2. This format uses empty lines to detect braces and attributes. 
#      If you have to specify multi-line values, increase the indentation for each new line.
# ===============================================================================

[Required]
{source_file_comment}
{source_file}= {source_file_default} 

{default_locale_comment}
{default_locale}= {default_locale_default}   

{available_locales_comment}
{available_locales}= {available_locales_default}


# =============================   OPTIONALS    =====================================
# Usually you will not need to edit this section.
# Here you can adjust where the generated files are saved and some settings to
# handle the behaviour of the QAutoLinguist
# ==================================================================================

[Optionals]
{translations_folder_comment}
{translations_folder}= {translations_folder_default}

{source_files_folder_comment}
{source_files_folder}= {source_files_folder_default}
     
{translatables_folder_comment}
{translatables_folder}= {translatables_folder_default}
        
{use_default_on_failure_comment}
{use_default_on_failure}= {use_default_on_failure_default}     

{revise_after_build_comment}
{revise_after_build}= {revise_after_build_default}      

{clean_comment}
{clean}= {clean_default}            

{debug_mode_comment}
{debug_mode}= {debug_mode_default}               

{verbose_comment}
{verbose}= {verbose_default}   
"""

# =============================   INTERNAL    ====================================================
# Section containing special values and attributes for the correct functioning of QAutoLinguist. 
# Any changes to these values will prevent QAutoLinguist from working properly.
# ================================================================================================